name = "IterativeRefinement"
uuid = "bcb6b82e-7479-5933-8c8e-2e0b909ee6a3"
version = "0.2.2-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[weakdeps]
ArnoldiMethod = "ec485272-7323-5ecc-a04f-4719b315124d"

[extensions]
ArnoldiExt = "ArnoldiMethod"

[compat]
julia = "1"
Aqua = "0.8"
ArnoldiMethod = "0.4"
LinearAlgebra = "1"
Quadmath = "0.5"
Random = "1"
Test = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
ArnoldiMethod = "ec485272-7323-5ecc-a04f-4719b315124d"
Quadmath = "be4d8f0f-7fa4-5f49-b795-2f01399ab2dd"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test","Random","Quadmath","ArnoldiMethod","Aqua"]
