name = "IterativeRefinement"
uuid = "bcb6b82e-7479-5933-8c8e-2e0b909ee6a3"
version = "0.2.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Quadmath = "be4d8f0f-7fa4-5f49-b795-2f01399ab2dd"

[targets]
test = ["Test","Random","Quadmath"]
